name: 'Visual Studio VSIX Signer'
description: 'Sign your Visual Studio extensions with ease!'
author: 'Coding with Calvin'
branding:
  color: purple
  icon: upload-cloud
inputs:
  sign-certificate-path:
    required: true
    description: 'Relative path to your publish manifest'
  vsix-path:
    required: true
    description: 'Relative path to your VSIX file'
  sign-password:
    required: true
    description: 'The password for your certificate file'
  vs-version:
    description: 'Version of Visual Studio to search; defaults to latest if not specified'
    required: false
  vs-prerelease:
    description: 'Enable searching for pre-release versions of Visual Studio'
    required: false        
runs:
  using: 'node16'
  main: 'dist/index.js'
